version: '3.2'
services:
  metastore:
    build:
      context: ./metastore
    ports:
      - "1527:1527"
    volumes:
      - "./data/_metastore:/mnt/database"
    environment:
      DB_DIR: "/mnt/database"

  polynote:
    build:
      context: ./polynote
    depends_on:
      - metastore
    command: ["--config", "/opt/polynote/config.yml"]
    ports:
      - "8080:8192"
      - "4040-4050:4040-4050"
    volumes:
      - "./polynote/config.yml:/opt/polynote/config.yml"
      - "./polynote/notebooks:/mnt/notebooks"
      - "/mnt/c/Users/pag/Documents/SDL_local/run/data:/mnt/data"
      - "/mnt/c/Users/pag/Documents/SDL_local/run/config:/mnt/config" # SDL config to use DataObjects in notebooks

networks:
  default:
    name: spark
